Web/TechDess.Web/Controllers/ProductTypesController.cs
namespace TechDess.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TechDess.Services.Data.ProductTypes;
    using TechDess.Web.ViewModels.ProductTypes;

    public class ProductTypesController : Controller
    {
        private readonly IProductTypesService productTypesService;

        public ProductTypesController(IProductTypesService productTypesService)
        {
            this.productTypesService = productTypesService;
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductTypeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.productTypesService.CreateAsync(input);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/TechDess.Web/Views/ProductTypes/Create.cshtml
@model TechDess.Web.ViewModels.ProductTypes.ProductTypeInputModel
@{
    this.ViewData["Title"] = "Add to productType";
}
<form metod="post" asp-area="" asp-controller="ProductTypes" asp-action="Create" class="col-md-6 offset-md-3" enctype="multipart/form-data">
    <h1>@this.ViewData["Title"]</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <input type="submit" class="btn btn-primary" />
</form>