Web/TechDess.Web/Controllers/ContactsController.cs
namespace TechDess.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using TechDess.Common;
    using TechDess.Data.Common.Repositories;
    using TechDess.Data.Models;
    using TechDess.Web.ViewModels.Contacts;

    public class ContactsController : BaseController
    {
        private const string RedirectedFromContactForm = "RedirectedFromContactForm";

        private readonly IRepository<ContactForm> contactsRepository;
        private readonly Microsoft.AspNetCore.Identity.UI.Services.IEmailSender emailSender;

        public ContactsController(IRepository<ContactForm> contactsRepository, Microsoft.AspNetCore.Identity.UI.Services.IEmailSender emailSender)
        {
            this.contactsRepository = contactsRepository;
            this.emailSender = emailSender;
        }

        [Authorize]
        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Index(ContactFormViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var contactFormEntry = new ContactForm
            {
                Name = model.Name,
                Email = model.Email,
                Title = model.Title,
                Content = model.Content,
            };
            await this.contactsRepository.AddAsync(contactFormEntry);
            await this.contactsRepository.SaveChangesAsync();

            var content = "Name: " + model.Name;
            content += "<br>Email: " + model.Email;
            content += "<br>Title: " + model.Title;
            content += "<br>Content: " + model.Content;

            this.ViewBag.msg = MailHelper.Send(model.Email, GlobalConstants.SystemEmail, model.Title, content);
            this.TempData[RedirectedFromContactForm] = true;

            return this.RedirectToAction("ThankYou");
        }

        public IActionResult ThankYou()
        {
            if (this.TempData[RedirectedFromContactForm] == null)
            {
                return this.NotFound();
            }

            return this.View();
        }
    }
}

Web/TechDess.Web/Controllers/OrdersController.cs
namespace TechDess.Web.Controllers
{
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TechDess.Services.Data.Orders;
    using TechDess.Services.Data.Receipts;
    using TechDess.Web.ViewModels.Orders;
    using TechDess.Web.ViewModels.Products;

    public class OrdersController : Controller
    {
        private readonly IOrdersService ordersService;
        private readonly IReceiptsService receiptsService;

        public OrdersController(IOrdersService ordersService, IReceiptsService receiptsService)
        {
            this.ordersService = ordersService;
            this.receiptsService = receiptsService;
        }

        public IActionResult Cart()
        {
            var viewModel = new ListOrderCartViewModel()
            {
                OrderCartViewModels = this.ordersService.GetAll<OrderCartViewModel>()
                        .Where(x => x.StatusName == "Active" && x.UserId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value),
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Increase(int id)
        {
            bool result = await this.ordersService.IncreaseQuantity(id);

            if (result)
            {
                return this.RedirectToAction(nameof(this.Cart));
            }
            else
            {
                return this.Forbid();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Reduce(int id)
        {
            bool result = await this.ordersService.ReduceQuantity(id);

            if (result)
            {
                return this.RedirectToAction(nameof(this.Cart));
            }
            else
            {
                return this.Forbid();
            }
        }

        [HttpPost]

        public async Task<IActionResult> Complete()
        {
            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var receiptId = await this.receiptsService.CreateReceipt(userId);
            return this.Redirect($"/Receipts/Profile/{receiptId}");
        }
    }
}

Web/TechDess.Web/Controllers/ProductsController.cs
namespace TechDess.Web.Controllers
{
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TechDess.Data.Common.Repositories;
    using TechDess.Data.Models;
    using TechDess.Services.Data.Cloudinary;
    using TechDess.Services.Data.Orders;
    using TechDess.Services.Data.Products;
    using TechDess.Services.Data.ProductTypes;
    using TechDess.Web.ViewModels.Orders;
    using TechDess.Web.ViewModels.Products;
    using TechDess.Web.ViewModels.ProductTypes;

    public class ProductsController : Controller
    {
        private readonly IProductsService productsService;
        private readonly IProductTypesService productTypesService;
        private readonly ICloudinaryService cloudinaryService;
        private readonly IOrdersService ordersService;

        public ProductsController(IProductsService productsService, IProductTypesService productTypesService, ICloudinaryService cloudinaryService, IOrdersService ordersService)
        {
            this.productsService = productsService;
            this.productTypesService = productTypesService;
            this.cloudinaryService = cloudinaryService;
            this.ordersService = ordersService;
        }

        public IActionResult Create()
        {
            var productTypes = this.productTypesService.GetAll<ProductTypeDropDownViewModel>();
            var viewModel = new ProductCreateInputModel()
            {
                ProductTypes = productTypes,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var image = await this.cloudinaryService.UploadPictureAsync(input.Image, input.Name);

            var productId = await this.productsService.CreateAsync(input, image);
            this.TempData["InfoMessage"] = "Product created!";
            return this.RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input, int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 8;
            var viewModel = new ProductListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = page,
                Count = this.productsService.GetCount(),
                Products = this.productsService.GetByProductTypes<ProductInListViewModel>(input.Id, page, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var product = this.productsService.GetById<SingleProductViewModel>(id);
            return this.View(product);
        }

        public IActionResult Increasing(SearchListInputModel input, int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 8;
            var viewModel = new ProductListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = page,
                Count = this.productsService.GetCount(),
                Products = this.productsService.GetAllIncreasing<ProductInListViewModel>(input.Id, page, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult Decreasing(SearchListInputModel input, int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 8;
            var viewModel = new ProductListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = page,
                Count = this.productsService.GetCount(),
                Products = this.productsService.GetAllDecreasing<ProductInListViewModel>(input.Id, page, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult SearchByTerm(ProductListViewModel input)
        {
            var viewModel = new ProductListViewModel()
            {
                Products = this.productsService.SearchByTerm<ProductInListViewModel>(input.SearchTerm),
                SearchTerm = input.SearchTerm,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await this.productsService.DeleteAsync(id);

            return this.RedirectToAction("Index", "Home");
        }

        public IActionResult Edit(int id)
        {
            var inputModel = this.productsService.GetById<CreateEditInputModel>(id);
            inputModel.ProductTypes = this.productTypesService.GetAll<ProductTypeDropDownViewModel>();
            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CreateEditInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.ProductTypes = this.productTypesService.GetAll<ProductTypeDropDownViewModel>();
                return this.View(input);
            }

            await this.productsService.UpdateAsync(id, input);
            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [HttpPost]
        public async Task<IActionResult> Order(OrderInputModel input)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var order = new CreateOrderModel()
            {
                UserId = userId,
                ProductId = input.ProductId,
                Quantity = input.Quantity,
            };
            order.StatusId = await this.ordersService.Create(order);
            return this.RedirectToAction("Cart", "Orders");
        }
    }
}

Web/TechDess.Web/Controllers/ServicesController.cs
namespace TechDess.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class ServicesController : Controller
    {
        public IActionResult ChooseDevice()
        {
            return this.View();
        }

        public IActionResult LoyalOffers()
        {
            return this.View();
        }

        public IActionResult Warranty()
        {
            return this.View();
        }

        public IActionResult Installations()
        {
            return this.View();
        }

        public IActionResult Courier()
        {
            return this.View();
        }

        public IActionResult Return()
        {
            return this.View();
        }
    }
}

Web/TechDess.Web/Views/Shared/_Layout.cshtml
@using TechDess.Common
@using TechDess.Data.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/fontawesome.min.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-light  border-bottom box-shadow mb-3" style="background-color: #483d8b;">
        <div class="container">
            <a class="navbar-brand font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="ProductTypes" asp-action="Create">CreateType</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Create">Create</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="SearchProducts" asp-action="Index">Search by brand</a>
                    </li>
                    <li class="dropdown">
                        <button class="btn btn-group-vertical text-white dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Services
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="Services" asp-action="ChooseDevice">How to choose a device</a>
                            <a class="dropdown-item" asp-controller="Services" asp-action="Courier">Delivery to the courier office</a>
                            <a class="dropdown-item" asp-controller="Services" asp-action="Installations">Installations</a>
                            <a class="dropdown-item" asp-controller="Services" asp-action="Return">60 days right of return</a>
                            <a class="dropdown-item" asp-controller="Services" asp-action="Warranty">Extended warranty</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-2">
            <div class="shopping-item">
                <a asp-controller="Orders"asp-action="Cart">Cart<i class="fa fa-shopping-cart"></i></a>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <partial name="_CookieConsentPartial" />
    <main role="main" class="pb-3">
        @this.RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
<script src="~/js/site.min.js" asp-append-version="true"></script>
@await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    $('.dropdown-toggle').dropdown()
</script>

Web/TechDess.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="List" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="List" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="List" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="List" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>